services:
  - type: web
    name: bedside
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn bedside.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.0"
      - key: DATABASE_URL
        fromDatabase:
          name: bedside_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "false"
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: "bedside.settings"

databases:
  - name: bedside_db
    databaseName: bedside
    user: bedside
    plan: free
